### ISSUE TITLE
Install fails with : Error response from daemon: can't create 'AutoRemove' container with restart policy

### ISSUE THREAD

**Issue by Wobak** [kasmtech/workspaces-issues#188]
Hello,

I'm trying to install kasm on a CentOS 8-Stream system.

I have docker & compose (btw not sure why you're using docker compose and not docker-compose).

During the install here is what I get : 
```
Setting Seed file as /opt/kasm/1.10.0/conf/database/seed_data/default_properties.yaml
Error response from daemon: Cannot kill container: kasm_db: No such container: kasm_db
Error: No such container: kasm_db
kasm_db_1.10.0
kasm_db_1.10.0
[+] Running 1/1
 ⠿ Container kasm_db  Started                                                                                                                     2.8s
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
Error response from daemon: can't create 'AutoRemove' container with restart policy
```

Which seems logical when I see that db_init contains this : 
```
docker compose  -f ${KASM_INSTALL_BASE}/docker/.conf/docker-compose-api.yaml run -v ${SEED_FILE}:/tmp/${SEED_FILE_NAME} --rm --entrypoint "/usr/bin/kasm_server.so ${INITIALIZE_DATABASE} --cfg /opt/kasm/current/conf/app/api.app.config.yaml --populate-production --seed-file /tmp/${SEED_FILE_NAME}" kasm_api
```

While the compose.yml contains : 
```
# cat docker/docker-compose-api.yaml
version: '3'
services:
  kasm_api:
    container_name: kasm_api
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/api:1.10.0"
    networks:
      - kasm_default_network
    volumes:
      - /opt/kasm/1.10.0:/opt/kasm/current
    **restart: always**
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
```

If I correct this by commenting the "restart: " section in the yml, I then get an error in the api container : 
```
Traceback (most recent call last):
  File "api_server/server.py", line 58, in <module>
Exception: Unable to find config /opt/kasm/current/conf/app/api.app.config.yaml
[7] Failed to execute script 'server' due to unhandled exception!

```

While the file exists : 
```
# ls /opt/kasm/1.10.0/conf/app/api.app.config.yaml -l
-rw-r--r-- 1 kasm kasm 7404 Apr  7 23:17 /opt/kasm/1.10.0/conf/app/api.app.config.yaml
```

Which feels like some things might not be working as expected.

Details of environment: 

```
# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

# docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.13
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:44 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
