### ISSUE TITLE
[Bug] - Unable to Complete Installation on Docker

### ISSUE THREAD

**Issue by SxthGear** [kasmtech/workspaces-issues#741]
**Describe the bug**
After starting the docker container, I am able to successfully navigate to the install page. After agreeing to the EULA, setting an admin password and user password, I am able to select the images I want to install. Clicking "Install" brings the terminal page up where the error occurs.

**To Reproduce**
Click install button on images page. Any or all images produces the same outcome.

**Expected behavior**
Image is installed and webui is accessible.

**Screenshots**
Terminal output:

```
Installing docker rclone plugin
amd64: Pulling from rclone/docker-volume-rclone
Digest: sha256:357122fb1d4cd42d1e4166e023d1b9a088ad33e6b676571589d64bf801bee445
c360c17c2d8f: Waiting
c360c17c2d8f: Pulling fs layer
c360c17c2d8f: Download complete
c360c17c2d8f: Complete
Installed plugin rclone/docker-volume-rclone:amd64
Setting Default Listening Port as 444
Setting Default Admin Password from stdin -P
Setting Default User Password from stdin -U
Installing All Services
Error: stat /opt/kasm/1.16.1/conf/app/api.app.config.yaml: no such file or directory
```

Docker console has single error:
```
    time=2025-05-26T04:47:41Zlevel=errormsg=2025/05/26 04:47:41 INFO : Serving unix socket: /run/docker/plugins/rclone.sockplugin=5e341789ae31a1bfe84109e24a318b66a2c6d8f4653cd3949289b9b52ee96cdd
```

**Workspaces Version**
Version 1.17

**Workspaces Installation Method**
Docker-Compose:

```
services:
  kasm:
    image: linuxserver/kasm:1.17.0
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optional
    environment:
      - KASM_PORT=444
    volumes:
      - /docker/containers/kasm/opt:/opt
      - /docker/containers/kasm/profiles:/profiles #optional
    ports:
      - 3068:3000
      - 444:444
    restart: unless-stopped
networks: {}
```

**Client Browser (please complete the following information):**
 - OS: Win 11
 - Firefox
 - Version 138

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**
Same error even if volume is not mapped to `/opt`
