### ISSUE TITLE
[Bug] - Registry is not updated

### ISSUE THREAD

**Issue by TheZoker** [kasmtech/workspaces-issues#750]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When I update the registry, new images are missing (like alpine 3.12 or ubuntu noble etc.):

<img width="1196" alt="Image" src="https://github.com/user-attachments/assets/4b11b5a4-f12b-4d78-8d3c-4f03735f59dd" />

**To Reproduce**
1. Go to 'Registry'
2. Press 'Update'

**Expected behavior**
Show new available workspaces

**Screenshots**
See above

**Workspaces Version**
none

**Workspaces Installation Method**
Single server with docker compose:
```yml
services:
  kasm:
    image: lscr.io/linuxserver/kasm
    container_name: Kasm
    restart: always
    privileged: true
    security_opt:
      - apparmor:rootlesskit
    ports:
      - 443:443
      - 3000:3000
    volumes:
      - /home/docker/files/kasm/data:/opt
      - /home/docker/files/kasm/profiles:/profiles
    environment:
      - TZ=Europe/Berlin
      - KASM_PORT=443
      - PUID=1000
      - PGID=1000
```

**Client Browser (please complete the following information):**
 - OS: macOS
 - Browser: arc
 - Version: 1.97.1

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**
